SELECT *
FROM HUNTERS_DB.RAW.AWS_CLOUDTRAIL
WHERE EVENT_TIME BETWEEN '2021-12-20' AND '2021-12-25'
  AND event_name = 'RunInstances'
--   AND RESPONSE_ELEMENTS ilike '%instanceName%'
LIMIT 10;

SELECT RESPONSE_ELEMENTs
FROM HUNTERS_DB.RAW.AWS_CLOUDTRAIL
WHERE EVENT_TIME BETWEEN '2021-12-20' AND '2021-12-25'
  AND EVENT_NAME = 'CreateUser'
  AND RESPONSE_ELEMENTS: user:userName ILIKE '%CHARGepo%'
ORDER BY EVENT_TIME DESC
LIMIT 100;

SELECT *
FROM HUNTERS_DB.RAW.AWS_CLOUDTRAIL
WHERE EVENT_TIME BETWEEN '2021-12-19' AND '2021-12-22'
  AND EVENT_NAME = 'ConsoleLogin'
--   AND USER_AGENT ILIKE '%python%'
ORDER BY EVENT_TIME DESC
limit 100;

SELECT *
FROM HUNTERS_DB.RAW.AWS_CLOUDTRAIL
WHERE EVENT_TIME > dateadd(day, -14, current_timestamp())
  AND EVENT_NAME = 'ConsoleLogin'
  AND USER_IDENTITY_ARN ILIKE '%michael%'
ORDER BY EVENT_TIME DESC
limit 100;


