SELECT AGENT_ID,
       MIN(START_TIME) AS first_seen,
       MAX(END_TIME)   AS last_seen
  FROM HUNTERS_DB.INVESTIGATION.EDR_AIDS_EXTERNAL_IPS_OLD
 WHERE EXTERNAL_IP = '87.71.217.98'
 GROUP BY AGENT_ID
 LIMIT 100;

SELECT AGENT_ID, EXTERNAL_IP
  FROM HUNTERS_DB.INVESTIGATION.EDR_AIDS_EXTERNAL_IPS_OLD
 LIMIT 100;

SELECT IMAGE_FILE_NAME,
       COMMAND_LINE,
       COUNT(*)        occurrences,
       MIN(EVENT_TIME) first_seen,
       MAX(EVENT_TIME) last_seen
  FROM HUNTERS_DB.RAW.CROWDSTRIKE_RAW_EVENTS
 WHERE aid = '1abe2a95be1045a2819bd2f0452516f8'
   AND EVENT_TIME > CURRENT_TIMESTAMP - INTERVAL '7 day'
   AND EVENT_SIMPLE_NAME IN ('ProcessRollup2', 'SyntheticProcessRollup2')
   AND COMMAND_LINE IS NOT NULL
 GROUP BY 1, 2
 ORDER BY occurrences DESC;